### PR TITLE
Fix #37 - Support isort >= 5

### LINKED ISSUE #37: Support for isort 5
isort 5 no longer have `SortImports` function and thus vim-isort doesn't work.

### PR DESCRIPTION
**Pull request by ziima**
Fix for the change of API in isort.

### CODE REVIEW

**Comment by ziima** [comment]
Fixed also loading of isort config.

**Comment by fisadev** [comment]
Great! I'll review it later today, but thanks in advance :)

**Comment by fisadev** [comment]
It has a bug, it won't work when no isort is present (will raise an ImportError). This is because of this structure:

```python
try:
    # import isort 5
except ImportError:
    # import isort older
except ImportError:
    # handle no insort
```

If the bit that tries to import an older isort fails, the second except won't be used. In python, the excepts only apply to the code from the try block, they don't apply to other except blocks. If you want to catch a possible exception inside an except block, you need a new try/except, like this:

```python
try:
    # import isort 5
except ImportError:
    try:
        # import isort older
    except ImportError:
        # handle no insort
```

**Comment by ziima** [comment]
:facepalm: Fixed.

**Comment by fisadev** [comment]
Merged! thanks for the fix :)

**Pull request merged**
